markdown: GFM
theme: minima
header_pages:
  - index.md
  - vintage_computers.md
  - retro_gaming.md
  - diy.md
minima:
  social_links:
    - { platform: x, user_url: "https://x.com/teki", title: "x/teki" }
title: teki page
author:
description:
